### ISSUE TITLE
can this emulate standard interrupts?

### ISSUE THREAD

**Issue by rs1909** [ivanizag/rust-z80#1]
Hi, I have seen that NMI is emulated, but I cannot see how IRQ is emulated. Am I missing something?

**Comment by ivanizag** [comment]
No. IRQ are not emulated in the current version. It wasn't needed yet on the projects I have used the library, and that's what drives the feature set. If you want to try adding IRQ support, it shouldn't be extra hard.

**Comment by ivanizag** [comment]
FYI. I just added maskable interrupts mode 1 as needed by https://github.com/ivanizag/z80-mbc2-emu.
