### ISSUE TITLE
License difference

### ISSUE THREAD

**Issue by anisse** [ivanizag/rust-z80#2]
Hi,

It seems Cargo.toml and the recent LICENSE file have a different license, would it possible to update one of them ?

Thanks a lot for this emulator, especially the tests :-)

**Comment by ivanizag** [comment]
You are right! I am always lots with all the options available.

I am happy that you find this useful for your projects. Note that for some of the tests, I have taken resource files with unclear licensing used on several projects. See https://github.com/ivanizag/iz80/blob/master/tests/res/origin.txt

**Comment by anisse** [comment]
Thanks, I noticed that, and I'll be sure to take it into account and use the proper licenses/citations.

**Comment by anisse** [comment]
Regarding the syntax of the Cargo.toml license line, do you know if it's case sensitive ? I could not find an answer [in the docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields); I'm not sure it's relevant.

**Comment by ivanizag** [comment]
Let's play safe and use the short identifier case from https://github.com/spdx/license-list-data/blob/v3.11/licenses.md
Thanks.

**Comment by anisse** [comment]
Thanks a lot !
